#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect create a redirect page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

# Prepare the string for replacing
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-enabled/default

sudo service nginx restart
