#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect create a redirect page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

# Prepare the string for replacing
string_for_replacement="server_name _;\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
