#!/usr/bin/env bash
# Script that configures a new Ubuntu server by creating a homepage,
#+	redirect page and a custom 404 error page

# First ensure that the packages are updated and nginx is installed
sudo apt-get update
sudo apt-get install -y nginx

# Basic test to be shown on the homepage
echo "Hello World!" | sudo tee /var/www/html/index.html

# Backup the original Nginx default site configuration
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

# Using Sed to add a custom redirect page (redirect_me/) into the Nginx configurion
sudo sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Create a custom 404 error HTML file
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Using Sed to add a custom 404 error page into the Nginx configuration
sudo sed -i '/listen 80 default_server;/a \\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-enabled/default

# Restart Nginx service to apply the changes
sudo service nginx restart
