#!/usr/bin/env bash
# Configure a new ubuntu server 

# Updating Packages before performing installations
sudo apt-get update

# Installs nginx server
sudo apt-get -y install nginx
sudo apt-get install -y ufw
sudo ufw allow 'Nginx HTTP'

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Using Sed to add a custom redirect page (redirect_me/) into the Nginx configurion
sudo sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Create a custom 404 error HTML file
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Using Sed to add a custom 404 error page into the Nginx configuration
sudo sed -i '/listen 80 default_server;/a \\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Creating an HTTP response header and ensuring $hostname expands properly
sudo sed -i "/server {/a \\\tadd_header X-Served-By $HOSTNAME always;" /etc/nginx/sites-available/default

# Create a link to the sites-enabled directory
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart nginx after implementing changes
sudo service nginx restart
