#!/usr/bin/env bash
# A bash script that Install and configure HAproxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Variables representing the backend servers
WEB01="35.153.67.87"
WEB02="100.26.240.141"

# Update package index
sudo apt-get update

# Install HAProxy.
sudo apt-get -y install haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Writing new HAProxy configuration.
sudo bash -c 'cat << EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 462126-web-01 35.153.67.87:80 check
    server 462126-web-02 100.26.240.141:80 check
EOF'

# Check the new HAProxy configuration for errors.
sudo haproxy -f /etc/haproxy/haproxy.cfg -c

# Reload HAProxy service to apply the new configuration.
sudo systemctl reload haproxy
