#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend prinko.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 462126-web-01 35.153.67.87:80 check
	server 462126-web-02 100.26.240.141:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
