#!/usr/bin/env bash
# A Bash script of task 0 but making fix short and sweet (using less lines)
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
