#!/usr/bin/env bash
# A Bash script that displays a list of currently running processes.
#+      processes, for all users, including those without a TTY, 
#+      in a user-oriented format, with process hierarchy.
ps auxf
