#!/usr/bin/env bash
# A Bash script that displays 'To infinity and beyond' indefinitely.
#+ adding 'sleep 2' In between each iteration of the loop.

while true
do
echo "To infinity and beyond"
sleep 2
done
