#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server with the below requirements.
#+  `localhost` resolves to 127.0.0.2
#+  `facebook.com` resolves to 8.8.8.8.
#+  The checker is running on Docker

# Check if the script is running on Docker
if [ -f /.dockerenv ]; then
    # Configure /etc/hosts file
    echo "127.0.0.2 localhost" >> /etc/hosts
    echo "8.8.8.8 facebook.com" >> /etc/hosts
else
    echo "This script is intended to run on Docker."
    exit 1
fi
