#!/usr/bin/env bash
# a concise Bash script for shorter version of task1
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) default_server;/listen 8080 default_server; listen [::]:8080 default_server;/' /etc/nginx/sites-enabled/*
pkill apache2
service nginx restart
