#!/usr/bin/env bash
# a concise Bash script for shorter version of task1
pkill apache2
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
chown -R nginx:nginx /var/log/nginx /var/cache/nginx /var/run
service nginx restart
