#!/usr/bin/env bash
# a concise Bash script for shorter version of task1
adduser --system --no-create-home --shell /bin/false --group --disabled-login nginx
sed -i 's/listen[ ]*80;/listen 8080;/g' /etc/nginx/sites-available/default
sed -i '/user /c\user nginx;' /etc/nginx/nginx.conf
chown -R nginx:nginx /var/log/nginx /var/cache/nginx /var/run
nginx -s reload
